package com.ntduc.baseproject.constant

/**
 * Created by TruyenIT
 */

const val BASE_URL = "http://45.79.147.162:1234/"
const val SHARED_PREFERENCES_FILE_NAME = "task"
const val FAVOURITES_KEY = "favourites"

const val SORT_BY = "SORT_BY"
const val SORT_BY_NAME_A_Z = 1
const val SORT_BY_NAME_Z_A = 2
const val SORT_BY_DATE_NEW = 3
const val SORT_BY_DATE_OLD = 4
const val SORT_BY_SIZE_LARGE = 5
const val SORT_BY_SIZE_SMALL = 6

const val NAME_HEAD = "NAME_HEAD"
const val DATE_HEAD = "DATE_HEAD"
const val SIZE_HEAD = "SIZE_HEAD"

const val IS_FAVORITE = "IS_FAVORITE"
const val FAVORITE_APP = "FAVORITE_APP"
const val FAVORITE_APK = "FAVORITE_APK"
const val FAVORITE_DOCUMENT = "FAVORITE_DOCUMENT"
const val FAVORITE_AUDIO = "FAVORITE_AUDIO"
const val FAVORITE_IMAGE = "FAVORITE_IMAGE"
const val FAVORITE_VIDEO = "FAVORITE_VIDEO"

const val KEY_BASE_APK = "KEY_BASE_APK"
const val KEY_BASE_DOCUMENT = "KEY_BASE_DOCUMENT"
const val KEY_BASE_AUDIO = "KEY_BASE_AUDIO"
const val KEY_BASE_FOLDER_AUDIO = "KEY_BASE_FOLDER_AUDIO"
const val KEY_BASE_IMAGE = "KEY_BASE_IMAGE"
const val KEY_BASE_FOLDER_IMAGE = "KEY_BASE_FOLDER_IMAGE"
const val KEY_BASE_VIDEO = "KEY_BASE_VIDEO"
const val KEY_BASE_FOLDER_VIDEO = "KEY_BASE_FOLDER_VIDEO"

const val PLAYLIST_AUDIO = "PLAYLIST_AUDIO"